### ISSUE TITLE
create signup page

### ISSUE THREAD

**Issue by schmitty890** [schmitty890/sports-tracker#19]
Create a `/signup` handlebar template so we can route ourselves to the signup route

this way we can store all of our main pages under this `pages` folder to keep them organized

inside of that `pages` folder can live our `signup.handlebars` template

Here is the example from the ui template we are using. however if we wish to change this up and make it look different, that is fine as well. 🐶 
URL: https://blackrockdigital.github.io/startbootstrap-sb-admin-2/register.html
code: https://github.com/BlackrockDigital/startbootstrap-sb-admin-2/blob/master/register.html

**Comment by Habernet** [comment]
Can we use two different templating engines? If we can, is it worth it?
